# SPDX-License-Identifier: GPL-2.0
#
# Generic framework for controlling remote processors

ccflags-y += -I$(top)/include

obj-$(CONFIG_MTKCCD_REMOTEPROC) += mtk-ccd.o

# mtk-ccd.ko
mtk-ccd-objs += mtk_ccd.o
mtk-ccd-objs += mtk_ccd_mem.o
