# SPDX-License-Identifier: GPL-2.0

subdir-ccflags-y += -Werror

subdir-ccflags-y += -DISP7_0
obj-y += camsys/

subdir-ccflags-y += -DIMGSYS_VER_ISP70
subdir-ccflags-y += -DIMGSYS_WPE_NUM=2
subdir-ccflags-y += -DIMGSYS_TRAW_NUM=2
obj-y += imgsys/
obj-y += mtk-hcp/
obj-y += mtk-ipesys-me/
